//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int ProductGroupId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public bool Active { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
